// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK5Pp94I6R7uyTxYqoTZy-ViCaPSt7iMI',
    appId: '1:926432515290:web:c6ae1b7f48e12e5f3881e3',
    messagingSenderId: '926432515290',
    projectId: 'ambulance-ab686',
    authDomain: 'ambulance-ab686.firebaseapp.com',
    storageBucket: 'ambulance-ab686.firebasestorage.app',
    measurementId: 'G-WFC3J937VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEtyCRkXN3LWp7tNuWxnU9NWXfbS-Gcbk',
    appId: '1:926432515290:android:cb471612cce138143881e3',
    messagingSenderId: '926432515290',
    projectId: 'ambulance-ab686',
    storageBucket: 'ambulance-ab686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoSNhjVDLoO-NizPdcwgKZLjZsAvwoZiw',
    appId: '1:926432515290:ios:2b90d93a7f5e9e443881e3',
    messagingSenderId: '926432515290',
    projectId: 'ambulance-ab686',
    storageBucket: 'ambulance-ab686.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoSNhjVDLoO-NizPdcwgKZLjZsAvwoZiw',
    appId: '1:926432515290:ios:2b90d93a7f5e9e443881e3',
    messagingSenderId: '926432515290',
    projectId: 'ambulance-ab686',
    storageBucket: 'ambulance-ab686.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK5Pp94I6R7uyTxYqoTZy-ViCaPSt7iMI',
    appId: '1:926432515290:web:ee9d20b7d939e6103881e3',
    messagingSenderId: '926432515290',
    projectId: 'ambulance-ab686',
    authDomain: 'ambulance-ab686.firebaseapp.com',
    storageBucket: 'ambulance-ab686.firebasestorage.app',
    measurementId: 'G-CHLN53GR96',
  );
}
